version: "3.8"

services:
  springboot-app:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library-app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library-app
    volumes:
      - mysql-data:/var/lib/mysql
  volumes:
    mysql-data: ./data:/var/lib/mysql
