version: "3.8"

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DBURL: ep-purple-hill-a2287f2t.eu-central-1.pg.koyeb.app
      DBNAME: library-db
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_LSonkm0zGPX5
